### ISSUE TITLE
fromWindowOrigin_/

### ISSUE THREAD

**Issue by Daxten** [japgolly/scalajs-react#188] opened 2015-09-23 10:36 UTC
scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.String
....
 at japgolly.scalajs.react.extra.router2.BaseUrl$.fromWindowOrigin(http://localhost:9000/assets/client-fastopt.js:31063:3)

Got these in IE 11 on Win10 and IE 10 in general. Chrome and FF works fine. v 0.9.2

**Comment by japgolly** [comment] 2015-09-23 22:56
`window.origin` is called via scala-js-dom with the rule thus far being that anything there is acceptable here. You could please raise this issue with scala-js-dom?

**Comment by japgolly** [comment] 2015-10-20 21:56
Closing as the problem is that scala-js-dom is the culprit here. Please if something is changed on that side.

**Closed by japgolly** 2015-10-20 21:56 UTC
Labels: maybe, wontfix
