### ISSUE TITLE
SVG <.marker doesn't support orient, refX, and refY?

### ISSUE THREAD

**Issue by IanOlin** [japgolly/scalajs-react#471] opened 2018-06-22 00:38 UTC
This might be an issue on how I'm using it, but I can't seem to set the references and orientation on markers. Is this not supported yet or have I done something wrong?

**Comment by IanOlin** [comment] 2018-06-22 17:49
Resolved by using custom VdomAttrs. I'm going to leave the issue open in case this is actually a bug, feel free to close it if there's no plans to support these features though (or if they are supported and I'm just not seeing it).

**Comment by IanOlin** [comment] 2018-06-28 19:37
Hi @japgolly , sorry about the delay. Here's the custom VdomAttrs:
`      val orient = VdomAttr("orient")
      val refX = VdomAttr("refX")
      val refY = VdomAttr("refY")`

**Comment by japgolly** [comment] 2018-06-30 04:39
Oh I misunderstood the issue. The issue is that these attributes aren't included in scalajs-react? Ok that's an easy fix!

Closed via d76f2794

**Comment by japgolly** [comment] 2018-06-30 04:40
These attributes will be available out-of-the-box in the next release. If you encounter any more missing feel free to send a PR using the above commit as a guide. Cheers

**Closed by japgolly** 2018-06-30 04:39 UTC
