### ISSUE TITLE
Encountering synthetic event pooling issue in a Callback

### ISSUE THREAD

**Issue by pnachum** [japgolly/scalajs-react#407] opened 2017-08-17 13:08 UTC
I have a component that contains an `input`, with the state controlled by a backend.
```scala
case class State(
  text: String, 
  ...
)

class Backend(bs: BackendScope[Unit, State]) {

  def onTextChange(event: ReactEventI): Callback =
    bs.modState(s => s.copy(text = event.target.value))

  def render(s: State): ReactElement = {
    input(
      value := s.text,
      onChange ==> onTextChange,
    )
  }
}
```
However, this code causes a run-time error every time the input's value changes, since `event.target` is `null`. This is caused by React's [synthetic event pooling](https://facebook.github.io/react/docs/events.html#event-pooling)

The workaround I've found is to change `onTextChange` to this
```scala
  def onTextChange(event: ReactEventI): Callback = {
    val value = event.target.value;
    bs.modState(s => s.copy(text = value))
  }
```

I wonder if there's a more ergonomic and type-safe way to accomplish this.

**Comment by japgolly** [comment] 2017-08-17 13:26
Yeah, that's an annoying decision the React team made to buy performance.
Workaround is to use `.extract` (a scalajs-react addon, not part of React) on events.

Example: https://github.com/japgolly/scalajs-react/blob/master/gh-pages/src/main/scala/ghpages/examples/ProductTableExample.scala#L154-L155

**Comment by japgolly** [comment] 2017-08-17 13:27
(...which is just shorthand for what you already did.)

**Comment by pnachum** [comment] 2017-08-17 20:35
Ah, I see. Perhaps `event.target` should return an `Option[DOMEventTarget]`, to prevent run-time errors?

**Comment by japgolly** [comment] 2017-09-12 00:31
The problem with that is that you change the loud runtime error into a silent runtime error which is worse IMO. Also, this *is* a compile-time bug. It's entirely deterministic by a human looking at the code. The problem is it doesn't seem possible to prevent it as a compile-time error due to limitations of Scala's type system (without embedded a new one in it). I'd prefer compile-time error but seeing as that's impossible, I prefer loud runtime to silent runtime.

**Comment by japgolly** [comment] 2017-09-20 23:39
Closing cos I think this question has been answered. Feel free to re-open if needed.

**Closed by japgolly** 2017-09-20 23:39 UTC
Labels: question
